name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Get your code
      - uses: actions/checkout@v4

      # 2) Node 20 for firebase-tools@14
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Install pnpm and deps
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --no-frozen-lockfile

      # 4) Write the .env file so Vite picks up your Firebase client config
      - name: Generate .env for Vite
        run: |
          cat > .env <<'EOF'
          PUBLIC_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          PUBLIC_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          EOF

      # 4.5) Sanity check: show public pieces + lengths (no secrets printed)
      - name: Sanity check .env (redacted)
        run: |
          echo "----- PUBLIC FIELDS -----"
          grep -E 'PUBLIC_FIREBASE_(PROJECT_ID|AUTH_DOMAIN|STORAGE_BUCKET)=' .env || true
          echo "----- LENGTH CHECKS -----"
          awk -F= '/^PUBLIC_FIREBASE_API_KEY=/{printf("API_KEY length=%d\n", length($2))}' .env || true
          awk -F= '/^PUBLIC_FIREBASE_APP_ID=/{printf("APP_ID length=%d\n", length($2))}' .env || true
          awk -F= '/^PUBLIC_FIREBASE_MESSAGING_SENDER_ID=/{printf("MSG_SENDER_ID length=%d\n", length($2))}' .env || true

          

      - name: Assert kit present
        run: |
          pnpm ls @sveltejs/kit
          pnpm exec svelte-kit --version

      # 5) Build your SvelteKit app (adapter-static writes to ./build)
      
      - run: pnpm run build

      # 6) Deploy the build/ folder to your live channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUZZLEGAME_81846 }}
          projectId: puzzlegame-81846
          channelId: live
