name: Deploy to Firebase Hosting on merge  
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Pull down your code
      - uses: actions/checkout@v4

      # 2) Install Node.js 20.x so firebase-tools@14 will work
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3) Install PNPM (and your dependencies)
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # 4) Build your SvelteKit app
      - name: Build
        run: pnpm run build

      # 5) Deploy to Firebase Hosting live channel
      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}                            # GitHub token for status checks
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUZZLEGAME_81846 }}  
          projectId: puzzlegame-81846
          channelId: live
