name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) pull down your code
      - uses: actions/checkout@v4

      # 2) Use Node.js 20.x (required by firebase-tools@14.x)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Install pnpm itself
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 4) Install your dependencies
      - run: pnpm install --frozen-lockfile

      # 5) Build your SvelteKit app
      - run: pnpm run build

      # 6) Deploy to your live channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUZZLEGAME_81846 }}
          projectId: puzzlegame-81846
          channelId: live
